# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xTynFSvEGFelhrFyhCk09Y3rBq7OIkKu
"""

import streamlit as st
import google.generativeai as genai
import gspread
from google.oauth2.service_account import Credentials
import datetime
import pytz

# --- 1. KONFIGURASI HALAMAN ---
st.set_page_config(page_title="AURA AI", page_icon="✨")

# Header ala WhatsApp
col1, col2 = st.columns([1, 5])
with col1:
    st.image("profile_aura.jpeg", width=70)
with col2:
    st.subheader("AURA")
    st.caption("Online | Inisiatif AI Strategic Assistant")

# --- 2. KONEKSI DATABASE (MENGGUNAKAN SECRETS) ---
def init_connection():
    # Data diambil dari Streamlit Secrets untuk keamanan
    info = st.secrets["gcp_service_account"]
    creds = Credentials.from_service_account_info(info, scopes=["https://www.googleapis.com/auth/spreadsheets"])
    gc = gspread.authorize(creds)
    return gc.open_by_key(st.secrets["spreadsheet_id"])

try:
    sh = init_connection()
    sheet_harian = sh.worksheet("Chat_Harian")
    sheet_info = sh.worksheet("Personal_Information")

    genai.configure(api_key=st.secrets["GEMINI_API_KEY"])
    model = genai.GenerativeModel('gemini-2.5-flash')
except Exception as e:
    st.error(f"Koneksi terhambat: {e}")

# --- 3. LOGIKA WAKTU & MEMORI ---
def get_now():
    return datetime.datetime.now(pytz.timezone('Asia/Jakarta'))

if "messages" not in st.session_state:
    st.session_state.messages = []

# Tampilkan chat lama
for m in st.session_state.messages:
    with st.chat_message(m["role"]):
        st.markdown(m["content"])

# --- 4. INPUT USER & RESPON AURA ---
if prompt := st.chat_input("Ketik pesan untuk AURA..."):
    st.session_state.messages.append({"role": "user", "content": prompt})
    with st.chat_message("user"):
        st.markdown(prompt)

    # Ambil 100 baris terakhir & info personal
    info_data = sheet_info.get_all_values()
    konteks_personal = "\n".join([f"- {row[0]}" for row in info_data[1:]])

    chat_data = sheet_harian.get_all_values()
    konteks_chat = chat_data[-100:]

    waktu_skrg = get_now()
    prompt_system = f"""
    Kamu adalah AURA, Personal AI milik Ryan.
    Waktu: {waktu_skrg.strftime('%A, %d %B %Y %H:%M')} WIB.

    INFO PERMANEN RYAN: {konteks_personal}
    KONTEKS TERAKHIR: {konteks_chat}

    Tugas:
    1. Berikan respon cerdas, proaktif, dan akrab.
    2. Gunakan gaya 'Think with Google' untuk riset/tren.
    3. Jika input Jepang, berikan terjemahan & Romaji.
    """

    with st.chat_message("assistant"):
        response = model.generate_content([prompt_system, prompt])
        st.markdown(response.text)
        st.session_state.messages.append({"role": "assistant", "content": response.text})

    # Simpan ke Spreadsheet
    sheet_harian.append_row([waktu_skrg.strftime("%Y-%m-%d %H:%M:%S"), "User", prompt])
    sheet_harian.append_row([waktu_skrg.strftime("%Y-%m-%d %H:%M:%S"), "AURA", response.text])
